[build]
  base = "src/main/resources/static"
  publish = "/"
  command = "# no build command needed"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
