services:
  - type: web
    name: sistema-solar
    env: java
    plan: free
    region: oregon
    buildCommand: chmod +x mvnw && ./mvnw package -DskipTests
    startCommand: java -jar target/sistema-0.0.1-SNAPSHOT.jar
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
