services:
  - type: web
    name: solar-java
    runtime: java
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/sistema-0.0.1-SNAPSHOT.jar
    envVars:
      - key: PORT
        value: 8080
      - key: PYTHON_SERVICE_URL
        fromService:
          name: solar-python
          type: web
          property: url

  - type: web
    name: solar-python
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    rootDir: python_service
    envVars:
      - key: PORT
        value: 5000
